// <auto-generated />
using System;
using CantinhoSalgado_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CantinhoSalgado_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200629225124_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("CantinhoSalgado_API.Models.Comanda", b =>
                {
                    b.Property<int>("ComandaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEncomenda")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encomenda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("TEXT");

                    b.HasKey("ComandaID");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("CantinhoSalgado_API.Models.ComandaItens", b =>
                {
                    b.Property<int>("ComandaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComandaID1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoNome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoQtd")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComandaID");

                    b.HasIndex("ComandaID1");

                    b.ToTable("ComandaItens");
                });

            modelBuilder.Entity("CantinhoSalgado_API.Models.Estoque", b =>
                {
                    b.Property<int>("EstoqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdutoNome")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstoqueID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("CantinhoSalgado_API.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoNome")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProdutoPreco")
                        .HasColumnType("REAL");

                    b.HasKey("ProdutoID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("CantinhoSalgado_API.Models.ComandaItens", b =>
                {
                    b.HasOne("CantinhoSalgado_API.Models.Comanda", "Comanda")
                        .WithMany("Itens")
                        .HasForeignKey("ComandaID1");
                });

            modelBuilder.Entity("CantinhoSalgado_API.Models.Estoque", b =>
                {
                    b.HasOne("CantinhoSalgado_API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID");
                });
#pragma warning restore 612, 618
        }
    }
}
